# Generated by Django 4.0.3 on 2022-06-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_newstitle_newspaper_newsadmin_news_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsTitle',
            new_name='NewsPaperTitle',
        ),
        migrations.RenameField(
            model_name='newspaper',
            old_name='newsTitle',
            new_name='newsPaperTitle',
        ),
    ]
