# Generated by Django 4.0.3 on 2022-06-26 21:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_rename_newsinfo_newscomment_commentinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsPaper',
            new_name='NewsArtical',
        ),
    ]
